version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: postgres-db

    restart: always

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: leave_db

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: ./backend

    container_name: backend

    depends_on:
      - postgres

    ports:
      - "8000:8000"

    environment:
      DB_HOST: postgres
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: leave_db
      DB_PORT: 5432
      JWT_SECRET: your_secret_key

  frontend:
    build: ./frontend

    container_name: frontend

    depends_on:
      - backend

    ports:
      - "3000:80"

volumes:
  postgres-data: